In [2]:
import numpy as np



In [21]:
W = np.matrix([[0.6, 0.7 , 0], [0.01, 0.43, 0.88]])
w = np.matrix([[0.02], [0.03],[0.09]])
X = np.matrix([[0.75, 0.8],[0.2,0.05],[-0.75, 0.8],[0.2, -0.05]])
Y = np.matrix([[1],[1],[-1],[-1]])

for i in range(0,3):
    s = np.dot(X,W)
    print "s"
    print s

    sReLU = s.clip(min=0)
    print "\n sRelu"
    print sReLU

    sout = np.dot(sReLU,w)
    print "\n Sout"
    print sout

    yout = np.tanh(sout)
    print "\n yout"
    print yout

    Loss = 0.5*np.power((yout - Y),2)
    print "\n Loss"
    print Loss

    dSout = np.multiply(1 - np.power(np.tanh(sout),2),(yout - Y))
    print "\n dSout"
    print dSout

    #derivative of ReLU
    sReluDeriv = sReLU
    sReluDeriv[sReluDeriv>0] = 1
    D = np.multiply(sReluDeriv, np.dot(dSout, w.T))
    print "\n D"
    print D

    dW = np.dot(X.T, D)
    print "\n dW"
    print dW
    
    dWout = np.dot(sReLU.T, dSout)
    print "\n dWout"
    print dWout
    
    print "\n new W"
    W = W - 0.5*dW
    print W

    print "\n new Wout"
    w = w - 0.5*dWout
    print w
    print "=================="

s
[[ 0.458   0.869   0.704 ]
 [ 0.1205  0.1615  0.044 ]
 [-0.442  -0.181   0.704 ]
 [ 0.1195  0.1185 -0.044 ]]

 sRelu
[[ 0.458   0.869   0.704 ]
 [ 0.1205  0.1615  0.044 ]
 [ 0.      0.      0.704 ]
 [ 0.1195  0.1185  0.    ]]

 Sout
[[ 0.09859 ]
 [ 0.011215]
 [ 0.06336 ]
 [ 0.005945]]

 yout
[[ 0.09827181]
 [ 0.01121453]
 [ 0.06327535]
 [ 0.00594493]]

 Loss
[[ 0.40655687]
 [ 0.48884835]
 [ 0.56527723]
 [ 0.5059626 ]]

 dSout
[[-0.89301989]
 [-0.98866111]
 [ 1.05901824]
 [ 1.00590938]]

 D
[[-0.0178604  -0.0267906  -0.08037179]
 [-0.01977322 -0.02965983 -0.0889795 ]
 [ 0.          0.          0.09531164]
 [ 0.02011819  0.03017728  0.        ]]

 dW
[[-0.01332631 -0.01998946 -0.14955847]
 [-0.01628289 -0.02442433  0.00750291]]

 dWout
[[-0.87577163]
 [-0.87577163]
 [-0.82266277]]

 new W
[[ 0.60666315  0.70999473  0.07477924]
 [ 0.01814144  0.44221217  0.87624855]]

 new Wout
[[ 0.45788581]
 [ 0.46788581]
 [ 0.50133138]]
s
[[ 0.46951052  0.88626578  0.75708327]
 [ 0.1222397   0.164109